name: Fast geocode with renv

on:
  push:
    paths:
      - 'four-loko-sightings-raw.csv'
      - 'geocoder.R'
      - 'renv.lock'

jobs:
  geocode_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system libraries for terra
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libudunits2-dev

      - name: Restore renv cache
        uses: actions/cache@v3
        with:
          path: renv/library/R-4.3/x86_64-pc-linux-gnu
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: Restore packages with renv
        run: |
          Rscript -e 'install.packages("renv")'
          Rscript -e 'renv::restore()'

      - name: Run geocode script
        run: Rscript geocoder.R

      - name: Commit and push geocoded CSV if changed
