name: Geocode CSV on push

on:
  push:
    paths:
      - 'four-loko-sightings-raw.csv'
      - 'geocoder.R'

jobs:
  geocode_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("tidyverse", "tidygeocoder"))'

    - name: Run geocode script
      run: Rscript geocoder.R

    - name: Commit and push geocoded CSV if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add four-loko-sightings.csv
        git diff --cached --quiet || git commit -m "Auto update geocoded CSV [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
