name: Fast geocode with renv

on:
  push:
    paths:
      - 'four-loko-sightings-raw.csv'
      - 'geocoder.R'
      - 'renv.lock'

jobs:
  geocode_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Restore renv cache
      uses: actions/cache@v3
      with:
        path: renv/library
        key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
        restore-keys: ${{ runner.os }}-renv-

    - name: Restore packages with renv
      run: |
        Rscript -e 'install.packages("renv")'
        Rscript -e 'renv::restore()'

    - name: Run geocode script
      run: Rscript geocoder.R

    - name: Commit and push geocoded CSV if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add four-loko-sightings.csv
        git diff --cached --quiet || git commit -m "Auto update geocoded CSV [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
