name: Fast geocode with renv

on:
  push:
    paths:
      - 'four-loko-sightings-raw.csv'
      - 'geocoder.R'
      - 'renv.lock'

jobs:
  geocode_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system libraries for terra
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libudunits2-dev

      - name: Install renv
        run: Rscript -e 'install.packages("renv")'

      - id: get-path
        name: Get renv library path
        run: |
          Rscript -e 'cat(renv::paths$library(), file = "renv-lib-path.txt")'
          echo "cache-path=$(cat renv-lib-path.txt)" >> "$GITHUB_OUTPUT"

      - name: Restore renv cache (if exists)
        uses: actions/cache@v3
        with:
          path: ${{ steps.get-path.outputs.cache-path }}
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: Restore R packages with renv
        run: Rscript -e 'renv::restore()'

      - name: Ensure renv library path exists
        run: |
          mkdir -p "${{ steps.get-path.outputs.cache-path }}"

      - name: Save renv cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.get-path.outputs.cache-path }}
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: Run geocode script
        run: Rscript geocoder.R

      - name: Commit and push geocoded CSV if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add four-loko-sightings.csv
          git diff --cached --quiet || git commit -m "Auto update geocoded CSV [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
